"""Add checking column to cart_item table

Revision ID: c3426671f2dd
Revises: ebe218f0963d
Create Date: 2024-10-21 18:30:20.237937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3426671f2dd'
down_revision = 'ebe218f0963d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_recipe')
    op.drop_table('nutrition')
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checking', postgresql.ARRAY(sa.Boolean()), nullable=False))
        batch_op.create_unique_constraint('_cart_recipe_uc', ['cart_id', 'recipe_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('_cart_recipe_uc', type_='unique')
        batch_op.drop_column('checking')

    op.create_table('nutrition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='nutrition_cart_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.rid'], name='nutrition_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nutrition_pkey'),
    sa.UniqueConstraint('cart_id', 'recipe_id', name='_cart_recipe_uc')
    )
    op.create_table('favorite_recipe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.rid'], name='favorite_recipe_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_recipe_pkey')
    )
    # ### end Alembic commands ###
